// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecsegecdynnuesgccedk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjc2VnZWNkeW5udWVzZ2NjZWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzcyOTQsImV4cCI6MjA2NzYxMzI5NH0.tkfyUaNKN-7-HhfKATt7hY8iglF0PmdNYrrrpekONME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});